apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fwa4dewao-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fwa4dewao-python 
  name: fwa4dewao-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: fwa4dewao-python 
